/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTrustRouteImport } from './routes/_app.trust'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppMissionsRouteImport } from './routes/_app.missions'
import { Route as AppHealthRouteImport } from './routes/_app.health'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAutomationsRouteImport } from './routes/_app.automations'
import { Route as AppArtifactsRouteImport } from './routes/_app.artifacts'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppMissionsMissionIdRouteImport } from './routes/_app.missions.$missionId'
import { Route as AppChatMissionIdRouteImport } from './routes/_app.chat.$missionId'
import { Route as AppAutomationsJobIdRouteImport } from './routes/_app.automations.$jobId'
import { Route as AppArtifactsArtifactIdRouteImport } from './routes/_app.artifacts.$artifactId'
import { Route as AppApprovalsApprovalIdRouteImport } from './routes/_app.approvals.$approvalId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrustRoute = AppTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsRoute = AppMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppArtifactsRoute = AppArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsMissionIdRoute = AppMissionsMissionIdRouteImport.update({
  id: '/$missionId',
  path: '/$missionId',
  getParentRoute: () => AppMissionsRoute,
} as any)
const AppChatMissionIdRoute = AppChatMissionIdRouteImport.update({
  id: '/$missionId',
  path: '/$missionId',
  getParentRoute: () => AppChatRoute,
} as any)
const AppAutomationsJobIdRoute = AppAutomationsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AppAutomationsRoute,
} as any)
const AppArtifactsArtifactIdRoute = AppArtifactsArtifactIdRouteImport.update({
  id: '/$artifactId',
  path: '/$artifactId',
  getParentRoute: () => AppArtifactsRoute,
} as any)
const AppApprovalsApprovalIdRoute = AppApprovalsApprovalIdRouteImport.update({
  id: '/$approvalId',
  path: '/$approvalId',
  getParentRoute: () => AppApprovalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof AppApprovalsRouteWithChildren
  '/artifacts': typeof AppArtifactsRouteWithChildren
  '/automations': typeof AppAutomationsRouteWithChildren
  '/chat': typeof AppChatRouteWithChildren
  '/health': typeof AppHealthRoute
  '/missions': typeof AppMissionsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/trust': typeof AppTrustRoute
  '/approvals/$approvalId': typeof AppApprovalsApprovalIdRoute
  '/artifacts/$artifactId': typeof AppArtifactsArtifactIdRoute
  '/automations/$jobId': typeof AppAutomationsJobIdRoute
  '/chat/$missionId': typeof AppChatMissionIdRoute
  '/missions/$missionId': typeof AppMissionsMissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof AppApprovalsRouteWithChildren
  '/artifacts': typeof AppArtifactsRouteWithChildren
  '/automations': typeof AppAutomationsRouteWithChildren
  '/chat': typeof AppChatRouteWithChildren
  '/health': typeof AppHealthRoute
  '/missions': typeof AppMissionsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/trust': typeof AppTrustRoute
  '/approvals/$approvalId': typeof AppApprovalsApprovalIdRoute
  '/artifacts/$artifactId': typeof AppArtifactsArtifactIdRoute
  '/automations/$jobId': typeof AppAutomationsJobIdRoute
  '/chat/$missionId': typeof AppChatMissionIdRoute
  '/missions/$missionId': typeof AppMissionsMissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/approvals': typeof AppApprovalsRouteWithChildren
  '/_app/artifacts': typeof AppArtifactsRouteWithChildren
  '/_app/automations': typeof AppAutomationsRouteWithChildren
  '/_app/chat': typeof AppChatRouteWithChildren
  '/_app/health': typeof AppHealthRoute
  '/_app/missions': typeof AppMissionsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/trust': typeof AppTrustRoute
  '/_app/approvals/$approvalId': typeof AppApprovalsApprovalIdRoute
  '/_app/artifacts/$artifactId': typeof AppArtifactsArtifactIdRoute
  '/_app/automations/$jobId': typeof AppAutomationsJobIdRoute
  '/_app/chat/$missionId': typeof AppChatMissionIdRoute
  '/_app/missions/$missionId': typeof AppMissionsMissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/artifacts'
    | '/automations'
    | '/chat'
    | '/health'
    | '/missions'
    | '/settings'
    | '/trust'
    | '/approvals/$approvalId'
    | '/artifacts/$artifactId'
    | '/automations/$jobId'
    | '/chat/$missionId'
    | '/missions/$missionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/artifacts'
    | '/automations'
    | '/chat'
    | '/health'
    | '/missions'
    | '/settings'
    | '/trust'
    | '/approvals/$approvalId'
    | '/artifacts/$artifactId'
    | '/automations/$jobId'
    | '/chat/$missionId'
    | '/missions/$missionId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/approvals'
    | '/_app/artifacts'
    | '/_app/automations'
    | '/_app/chat'
    | '/_app/health'
    | '/_app/missions'
    | '/_app/settings'
    | '/_app/trust'
    | '/_app/approvals/$approvalId'
    | '/_app/artifacts/$artifactId'
    | '/_app/automations/$jobId'
    | '/_app/chat/$missionId'
    | '/_app/missions/$missionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trust': {
      id: '/_app/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof AppTrustRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/missions': {
      id: '/_app/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AppMissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health': {
      id: '/_app/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artifacts': {
      id: '/_app/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof AppArtifactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/missions/$missionId': {
      id: '/_app/missions/$missionId'
      path: '/$missionId'
      fullPath: '/missions/$missionId'
      preLoaderRoute: typeof AppMissionsMissionIdRouteImport
      parentRoute: typeof AppMissionsRoute
    }
    '/_app/chat/$missionId': {
      id: '/_app/chat/$missionId'
      path: '/$missionId'
      fullPath: '/chat/$missionId'
      preLoaderRoute: typeof AppChatMissionIdRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_app/automations/$jobId': {
      id: '/_app/automations/$jobId'
      path: '/$jobId'
      fullPath: '/automations/$jobId'
      preLoaderRoute: typeof AppAutomationsJobIdRouteImport
      parentRoute: typeof AppAutomationsRoute
    }
    '/_app/artifacts/$artifactId': {
      id: '/_app/artifacts/$artifactId'
      path: '/$artifactId'
      fullPath: '/artifacts/$artifactId'
      preLoaderRoute: typeof AppArtifactsArtifactIdRouteImport
      parentRoute: typeof AppArtifactsRoute
    }
    '/_app/approvals/$approvalId': {
      id: '/_app/approvals/$approvalId'
      path: '/$approvalId'
      fullPath: '/approvals/$approvalId'
      preLoaderRoute: typeof AppApprovalsApprovalIdRouteImport
      parentRoute: typeof AppApprovalsRoute
    }
  }
}

interface AppApprovalsRouteChildren {
  AppApprovalsApprovalIdRoute: typeof AppApprovalsApprovalIdRoute
}

const AppApprovalsRouteChildren: AppApprovalsRouteChildren = {
  AppApprovalsApprovalIdRoute: AppApprovalsApprovalIdRoute,
}

const AppApprovalsRouteWithChildren = AppApprovalsRoute._addFileChildren(
  AppApprovalsRouteChildren,
)

interface AppArtifactsRouteChildren {
  AppArtifactsArtifactIdRoute: typeof AppArtifactsArtifactIdRoute
}

const AppArtifactsRouteChildren: AppArtifactsRouteChildren = {
  AppArtifactsArtifactIdRoute: AppArtifactsArtifactIdRoute,
}

const AppArtifactsRouteWithChildren = AppArtifactsRoute._addFileChildren(
  AppArtifactsRouteChildren,
)

interface AppAutomationsRouteChildren {
  AppAutomationsJobIdRoute: typeof AppAutomationsJobIdRoute
}

const AppAutomationsRouteChildren: AppAutomationsRouteChildren = {
  AppAutomationsJobIdRoute: AppAutomationsJobIdRoute,
}

const AppAutomationsRouteWithChildren = AppAutomationsRoute._addFileChildren(
  AppAutomationsRouteChildren,
)

interface AppChatRouteChildren {
  AppChatMissionIdRoute: typeof AppChatMissionIdRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatMissionIdRoute: AppChatMissionIdRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppMissionsRouteChildren {
  AppMissionsMissionIdRoute: typeof AppMissionsMissionIdRoute
}

const AppMissionsRouteChildren: AppMissionsRouteChildren = {
  AppMissionsMissionIdRoute: AppMissionsMissionIdRoute,
}

const AppMissionsRouteWithChildren = AppMissionsRoute._addFileChildren(
  AppMissionsRouteChildren,
)

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRouteWithChildren
  AppArtifactsRoute: typeof AppArtifactsRouteWithChildren
  AppAutomationsRoute: typeof AppAutomationsRouteWithChildren
  AppChatRoute: typeof AppChatRouteWithChildren
  AppHealthRoute: typeof AppHealthRoute
  AppMissionsRoute: typeof AppMissionsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTrustRoute: typeof AppTrustRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRouteWithChildren,
  AppArtifactsRoute: AppArtifactsRouteWithChildren,
  AppAutomationsRoute: AppAutomationsRouteWithChildren,
  AppChatRoute: AppChatRouteWithChildren,
  AppHealthRoute: AppHealthRoute,
  AppMissionsRoute: AppMissionsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTrustRoute: AppTrustRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
